---
remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-remote-theme

avatar: "Avatar.png"
title: Ball Tracking Robot

navbar-links:
  Final Milestone: "https://nikdastick.github.io/NikolasMargaritisBlueStamp/#Final%20Milestone"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
markdown: kramdown
---
