---
remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-remote-theme

avatar: "Avatar.png"
title: Ball Tracking Robot

navbar-links:
  About Me: "[click on this link](#final-milestone)"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
markdown: kramdown
---
